png("piketty_labor_lorenz.png",width=640,height=640)
x<-piketty.labor
lorenz(x[,1],cumsum(x[,2]))
lines(x[,1],cumsum(x[,3]),col="blue")
lines(x[,1],cumsum(x[,4]),col="red")
lines(x[,1],cumsum(x[,5]),col="grey")
title(main="Lorenz Curve for Labor Income",xlab="Cumulative share of people fromlowest to highest",ylab="Cumulative share of income earned")
legend(x=0.05,y=0.95,legend=c("Low","Medium","High","Very High"),lty=1,col=c("black","blue","red","grey"),title="Income Inequality")
#axis(side=1,at=c(0.0,0.5,0.9,0.99,1.0),paste(c(0.0,0.5,0.9,0.99,1.0)))
dev.off()
png("piketty_capital_lorenz.png",width=640,height=640)
x<-piketty.co
lorenz(x[,1],cumsum(x[,2]))
lines(x[,1],cumsum(x[,3]),col="blue")
lines(x[,1],cumsum(x[,4]),col="red")
lines(x[,1],cumsum(x[,5]),col="grey")
lines(x[,1],cumsum(x[,6]),col="green")
title(main="Lorenz Curve for Capital Ownership",xlab="Cumulative share of people fromlowest to highest",ylab="Cumulative share of capital owned")
legend(x=0.05,y=0.95,legend=c("Low","Medium","Medium HIgh","High","Very High"),lty=1,col=c("black","blue","red","grey","green"),title="Capital Inequality")
#axis(side=1,at=c(0.0,0.5,0.9,0.99,1.0),paste(c(0.0,0.5,0.9,0.99,1.0)))
dev.off()
png("piketty_total_lorenz.png",width=640,height=640)
x<-piketty.total
lorenz(x[,1],cumsum(x[,2]))
lines(x[,1],cumsum(x[,3]),col="blue")
lines(x[,1],cumsum(x[,4]),col="red")
lines(x[,1],cumsum(x[,5]),col="grey")
title(main="Lorenz Curve for Total Income",xlab="Cumulative share of people fromlowest to highest",ylab="Cumulative share of income earned")
legend(x=0.05,y=0.95,legend=c("Low","Medium","High","Very High"),lty=1,col=c("black","blue","red","grey"),title="Income Inequality")
#axis(side=1,at=c(0.0,0.5,0.9,0.99,1.0),paste(c(0.0,0.5,0.9,0.99,1.0)))
dev.off()
